---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: demo-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/add-base-url: "true"
spec:
  rules:
  - host: "app.com"               # Domain name
    http:
      paths:
        - pathType: Prefix        # Loại path
          path: "/"               # Path   
          backend:
            serviceName: frontend-1
            servicePort: 8080
  - host: "api.app.com"
    http:
      paths:
        - pathType: Prefix
          path: "/be/?(.*)"               # Path   
          backend:
            serviceName: backend-1
            servicePort: 8080